CATALOGUE_HOST: catalogue.backend-{{ env }}.royalreddy.site
USER_HOST: user.backend-{{ env }}.royalreddy.site
CART_HOST: cart.backend-{{ env }}.royalreddy.site
SHIPPING_HOST: shipping.backend-{{ env }}.royalreddy.site
PAYMENT_HOST: payment.backend-{{ env }}.royalreddy.site