- name: install mysql 
  include_role:
    name: common
    tasks_from: mysql-setup.yaml

- name: start service mysql, if not started
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: install python3 
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  loop:
  - boto3
  - botocore
  
- name: setp root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }} # RoboShop@1